### ISSUE TITLE
DMS data mentioned in Fig. 5 exist?

### ISSUE THREAD

**Issue by luwei0917** [Gonglab-THU/EvoAI#1]
Great work!
May I ask where is the DMS data mentioned in Fig. 5? I can't find it.
Is it Extended Data Fig. 9a? but it's computed by model not from experiment.
Also, it doesn't match with Supplementary Table 4 I think.

Thanks.

**Comment by Gonglab-THU** [comment]
You can find the DMS data from source data Fig.5. If you have any questions, please feel free to ask.

**Comment by luwei0917** [comment]
Sorry for the confusion, but I was referring to the DMS data used to train EvoScan, not the data for the designed variants generated using the model trained on DMS information.

**Comment by Gonglab-THU** [comment]
1. The training of the EvoAI model did not use the DMS data of the AmeR protein.  
2. The "DMS data" mentioned in the article was used to train the GeoFitness model. For details about this data, refer to [this link](https://www.nature.com/articles/s43588-024-00716-2#data-availability).

**Comment by luwei0917** [comment]
So, is the heat map in Fig. 5d computed from the GeoFitness model (which was trained on some DMS data)? Is it the same as the heat map shown in Extended Data Fig. 9a?

**Comment by Gonglab-THU** [comment]
The heat map in Fig. 5d is computed from the GeoFitness model, which was trained on some DMS data. Additionally, it is the same heat map shown in Extended Data Fig. 9a.

If you have further questions, feel free to reach out!

**Comment by luwei0917** [comment]
Thanks.
