### ISSUE TITLE
Request for Information on Isotonic Optimization and Loss Function Definition

### ISSUE THREAD

**Issue by fourier20laplace** [Gonglab-THU/EvoAI#2]
![image](https://github.com/user-attachments/assets/5ac5e738-8121-4c17-8cec-96e4f737cd84)
1. Resources on Isotonic Optimization:
Could you kindly provide some resources or references on isotonic optimization? I am particularly interested in understanding the theoretical background and practical applications of this technique.
2. Difference Between Dual and Primal Solutions:
In the context of isotonic optimization, I noticed that the difference between the dual solution and the primal solution is defined as w. Could you explain why this difference is defined in this way and what significance w holds in this context?
3. Loss Function Definition:
I would also appreciate it if you could share some insights into the key considerations and motivations behind the choice of the loss function, and how does it impact the optimization process?
Thank you very much for your time and assistance. I look forward to your response.

**Comment by fourier20laplace** [comment]
![image](https://github.com/user-attachments/assets/ff1b4292-0d27-4dfa-a775-0b46619307ee)
Besides that, I noticed that the Projection.compute method returns (s-v), and when the mode is set to 'l2', it approximates the rank w. However, when the mode is set to 'kl' and the log(w) argument is passed, the loss function becomes <exp(s-v), 1> + <w, v>. In this case, the SoftRank.compute method returns exp(s-v), which I find a bit difficult to understand. Would you kindly help clarify whether my understanding is correct, and why the KL-based optimization process is designed this way? I would greatly appreciate your insights.

**Comment by Gonglab-THU** [comment]
The loss function we used is based on the [paper](https://doi.org/10.48550/arXiv.2002.08871), and the corresponding code repository can be found here: [https://github.com/google-research/fast-soft-sort](https://github.com/google-research/fast-soft-sort).  

However, we are not fully familiar with the specific details of this loss function, so we are unable to provide further support. I recommend directing your questions to the repository mentioned above: [https://github.com/google-research/fast-soft-sort](https://github.com/google-research/fast-soft-sort).

**Comment by fourier20laplace** [comment]
Thanks!
